app:
  restart: "no"
  build: ./app
  expose:
    - "8000"
  links:
    - postgres:postgres
  ports:
    - "8000:8000"

data:
  restart: "no"
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"
 
postgres:
  restart: "no"
  image: postgres:latest
  environment:
    - POSTGRESQL_DB=esgt
    - POSTGRESQL_USER=postgres
  volumes_from:
    - data
  expose:
    - "5432"
  ports:
    - "5432:5432"
