version: "3"

services:
  app:
    restart: "no"
    build:
      context: ./app
      dockerfile: Dockerfile-app
    expose:
      - "8000"
    links:
      - postgres:postgres
    ports:
      - "8000:8000"

  updater:
    restart: "no"
    build:
      context: ./app
      dockerfile: Dockerfile-updater
    links:
      - postgres:postgres

  postgres:
    restart: "no"
    image: postgres:latest
    environment:
      - POSTGRESQL_DB=esgt
      - POSTGRESQL_USER=postgres
    volumes:
      - data:/var/lib/postgresql
    expose:
      - "5432"
    ports:
      - "5432:5432"

volumes:
  data:
